### PR TITLE
Added new PostgreSQL auth method using env vars

### PR DESCRIPTION
**Pull request by tkopets**
Two new dict options under cli_options[type] are added in settings:
 * env - always sets the vars to given value
 * env_optional - sets the env vars only if sucessfully formatted

Default settings file is updated to support this new functionality.

Implementation for #106

### CODE REVIEW

**Comment by tkopets** [comment]
One more related thing to do is to update the comments in default (template) Connections file and mention this new functionality.
Will push one more commit to this PR with above changes shortly.

**Comment by tkopets** [comment]
@mtxr 
Does this look the right way to implement #106 to you?

**Comment by mtxr** [comment]
Yeah, it's perfect. Later we adopt some approach for the other SGDBs, but for now, PostgreSQL already have an alternative 🥇 !

Just please, update the docs at branch gh-pages later, ok?

**Comment by mtxr** [comment]
Btw, you are doing a great job @tkopets . Thank you very much for your help 😄 !

I'm a quite busy right now, but I'll be back fully recharged soon

**Comment by tkopets** [comment]
Thanks @mtxr, I'm more than happy to be able to contribute to this awesome project!

I've reviewed both readme and gh-pages and we need only a minor change there - will make those changes shortly.
By the way, this environment variables code can be universally applied to all supported RDBMS, so if we ever need to set some environment variables for those other RDBMS's for some reason - just add an `env` or `env_optional` section.

**Pull request merged**
