### PR TITLE
Show executed querie(s) and exec time

### PR DESCRIPTION
**Pull request by optio**
Show in the results panel a commnt that mentions the executed querie(s) and execute time.
Might be better to become optional.

### CODE REVIEW

**Comment by mtxr** [comment]
Can you make it optional?
Add some setting to the settings file,  by default should be false, than I can merge it without change current users workflow :)

**Comment by optio** [comment]
Indeed. Though how can I load the settings in Command.py, without passing it by changing the createAndRun() signature and adding a new param there?

**Comment by mtxr** [comment]
I think it's better to add some params like:
`def __init__(self, args, callback, query=None, encoding='utf-8',options={}):`

Than we can get some options there. I was thinking about something like this before but I'm a quite busy now :(

What do you think? any suggestions?

**Comment by optio** [comment]
Hoping you'll find a way to implement issue #19, the timer functionality in this pull request will have to be refactored, to append the execution time after the final 'streamed' result.

... Thank you for this awesome plugin!!

**Comment by mtxr** [comment]
I'm working on that. But it changes almost everything on the plugin architecture. 

Thanks! 

I hope to get it done by the end of the year, let's see :D

**Comment by optio** [comment]
OK, will make it optional and add new commits to this request

**Comment by optio** [comment]
Closing this request and will merge all in request 55

**Pull request closed without merging**
