### PR TITLE
Related to: #115

### PR DESCRIPTION
**Pull request by calope**
https://github.com/mtxr/SQLTools/issues/115

### CODE REVIEW

**Comment by tkopets** [comment]
This is a nice addition and as far as I understand the command "Describe Table" works as well with views in Oracle case. Can you confirm this (as I don't have Oracle connection to test)?

*Performance imrpovement*:
Since table names and view names cannot overlap, there is no need to do a `UNION` (which leaves only unique values), instead we would get a better performance of those queries if we use `UNION ALL`  instead of `UNION`.

**Comment by calope** [comment]
Confirm that it works correctly with the command describe table on Oracle Connection

**Comment by tkopets** [comment]
@calope 
Can you please push one more commit to this branch with `UNION ALL` improvement?

**Comment by calope** [comment]
@tkopets Ok.

18bca385572a5c6d9dd0cfefa8cc6aff1600625b

**Pull request merged**
